course_description = {'Calculus': "This is a college-level introductory calculus course designed to cover Differential Calculus (functions, limits, continuity, Intermediate Value Theorem, tangent lines, velocity, derivatives, rates of change, implicit differentiation, linear approximation, Mean Value Theorem, related rates, curve sketching, l’Hospital’s rule, and optimization problems); Integral Calculus (area, distance, Riemann sums, the Fundamental Theorem of Calculus, antiderivatives, integration techniques, and volume); and Differential Equations (slope fields, Euler’s Method, separation of variables, Newton’s Law of Cooling, and population growth).", 'Precalculus': "In this course, students continue their work from previous algebra and geometry courses by studying functions through graphical, numerical, and written representations. An emphasis is placed on exponential, logarithmic, rational, trigonometric, and inverse trigonometric functions. Additional topics to be investigated include sequences, series, and an introduction to limits. To enhance the understanding of these topics, data analysis and mathematical modeling of real world situations will be introduced. Technology is integrated throughout.", 'Algebra': 'In Advanced Algebra, students build on work from previous algebra and geometry courses to study a variety of function types. This course focuses on both the theory and applications of functions. Piecewise linear functions are used to review and reinforce the definitions of function, graph, domain, and range. Students extensively study quadratic functions and explore the mathematics behind polynomials, including operations applied to polynomials and rational functions. Exponential properties are revisited and extended to study nth roots and exponentials. Function composition and the concept of inverse functions are also introduced and reinforced with an introduction to logarithms. Applications involving quadratic optimization, compound interest, and exponential growth and decay models are included.'}
achievementDict = {1: f"your academic performance in this class has some room for improvement. I know you will be able to pull it off!", 2: f"your academic performance in this class has been phenomenal. I know you can do better!", 3: f"your academic performance in this class has been satisfactory. A little more effort would make you exceed the academic goal. You can do it!", 4: "your academic performance has been almost consistently well, with a little more consistency you will exceed in this class!", 5: "I appreciate the amount of effort you put in this class. They are shown in your very well-rounded academic achievement. Goodjob!"}

attentionDict = {1: f"You need to pay more attention in class, and stop being so easily distracted.", 2: f"Your attention levels in class are satisfactory, but there is still room for improvement.", 3: f"Your level of attention is good, but I know you can go further!", 4: f"Your level of attention in class is great, but you can get to the next level, I believe in you!", 5: f"The attention you pay in class is invaluable, and it really proves how good of a student you are"}

attendanceDict = {1: f"You need to work in your attendence, during this semester in this course you barely showed up to class.", 2: f"Your attendance during this semester in this course was below expectations. I know you can do better.", 3: f"Your attendance is alright, but you could show up to class in time more often.", 4: f"Your attendance this semester was great, apart from a couple of days you were always there.", 5: f"Your attendance is exceptional, you barely missed a minute of class this semester."}

homeworkDict = {1: f"You have many missing assignments in this course.", 2: f"Much of your homework was turned in late.", 3: f"You turned in some of your homework late you usually asked for an extension.", 4: f"You consistenly turned in your homework on time and you put effort into it and you asked for an extension whenever you couldn't complete an assignment.", 5: f"Your homework is consistently comeplete and turned in on time. You put effort into making sure that your assignments are complete to your best ability."}

gradeDict = {"A": f"That is why this semester I am awarding you an A.", "A-": f"That is why in this course you are being awarded an A-.", "B": f"I know you can push yourself further, that is why I must give you a B in this semester for this course.", "C": f"Unfortunately, your work this semester did not fully meet basic expectations that is why you earned a C."}

traitsDict = {"Funny": "Your humor brought to this class a very colorful and bright tone. You made this class feels more exciting. I appreciate that trait of you a lot.", "Leader": "Your leadership in this class has shown through many activities we have done in class. Your ability to lead people and keep your peers in place is amazing to me. I'm sure this trait of you will make you a great adult in the future.", "Lazy": "Regardless of how you do in class, I believe if you put a little more effort into this class it will be more beneficial for you. Keep going!", "Sleepy": "I appreciate your effort coming to attend the class so early in the morning, but you should be getting your sleep at home and not at school. I know you can do it!", "Quiet": "Eventhough you stay quiet and calm in all the class, I know you can work hard. Even when you collaborate with people not as much, your work quality has never dropped. I encourage you to ask questions or talk to your peers if that helps, but I believe your quiet trait does not give you any disadvantage in class at all!", "Hardworking": "I respect the amount of effort you put into this class. You are very hardworking and I'm sure this will help you exceed in college and future career. Goodjob!", "Engaged": "You always participate in class discusion and answer every questions even when you are unsure. I appreciate that courage of yours and hope you will continue to be an example for the rest of your class. Great job here!", "Insightful": "Your engagement in this class has been very insightful. The thoughts and opinion you bring in this class shows perspectives that other have not encounter before. Your assignments also clearly show all your thinking, way to go!" }
